name: 'Weather Notification Action'
description: '🌤️ 功能强大的天气通知Action，基于高德地图数据源'
author: 'Weather Notification Team'

branding:
  icon: 'cloud'
  color: 'blue'

inputs:
  # 天气API配置
  amap_api_key:
    description: '高德地图API密钥'
    required: true
  
  # 城市配置
  city:
    description: '城市名称或6位城市编码'
    required: false
    default: 'Beijing'
    
  # 邮件服务器配置
  smtp_host:
    description: 'SMTP服务器地址'
    required: false
    default: 'smtp.gmail.com'
    
  smtp_port:
    description: 'SMTP端口号'
    required: false
    default: '587'
    
  smtp_user:
    description: 'SMTP用户名（邮箱地址）'
    required: true
    
  smtp_pass:
    description: 'SMTP密码或应用专用密码'
    required: true
    
  # 收件人配置
  recipient_emails:
    description: '收件人邮箱地址，多个邮箱用逗号分隔'
    required: true
    
  # 邮件配置
  email_subject:
    description: '邮件主题（可选）'
    required: false
    
  sender_name:
    description: '发件人名称'
    required: false
    default: '天气通知助手'

outputs:
  status:
    description: '执行状态 (success/failure)'
  message:
    description: '执行结果消息'
  weather_data:
    description: '天气数据JSON字符串'
  recipients_count:
    description: '收件人数量'

runs:
  using: 'node20'
  main: 'dist/index.js' 